baseURL = 'https://thisisdavidjones.github.io'
languageCode = 'en-us'
title = 'The website of David Jones'
theme  = 'david'
enableGitInfo = true


[params]
    RSSLink = "/index.xml"
    author = "David Jones" # add your company name
    github = "" # add your github profile name
    twitter = "askdavidjones" # add your twitter profile
    email = "me@thisisdavidjones.com"
    dateFormat = "02 Jan 2006"
    googleAnalytics= 'G-67Z8EJXRP3'
    math = true

[permalinks]
    blog     =  "/blog/:year/:month/:slug"

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps =  false
    [markup.goldmark.parser.attribute]
      block = true
      title = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


