baseURL = 'https://thisisdavidjones.github.io'
languageCode = 'en-us'
title = 'The website of David Jones'
theme  = 'david'

[Params]
    RSSLink = "/index.xml"
    author = "David Jones" # add your company name
    github = "" # add your github profile name
    twitter = "askdavidjones" # add your twitter profile
    email = "me@thisisdavidjones.com"
    googlefonts = ["Alegreya", "Alegreya+SC"]
    fontbody = 'Alegreya'
    fontcode = 'Fira Mono'
    dateFormat = "02 Jan 2006"

[permalinks]
    blog     =  "/blog/:year/:month/:slug"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps =  false